from enum import IntEnum



"""
Reference:
https://www.mctechnology.nl/wp-content/uploads/2018/03/TMCL_reference_2015.pdf
"""

class StatusCodes(IntEnum):
    SUCCESSFULLY_EXECUTED = 100
    COMMAND_LOADED_INTO_EEPROM = 101
    WRONG_CHECKSUM = 1
    INVALID_COMMAND = 2
    WRONGE_TYPE = 3
    INVALID_VALUE = 4
    CONFIGURATION_EEPROM_LOCKED = 5
    COMMAND_NOT_AVAILABLE = 6


class MotionCommands(IntEnum):
    ROTATE_LEFT = 2
    ROTATE_RIGHT = 1
    MOVE_TO_POSITION = 4
    MOTOR_STOP = 3
    REFERENCE_SEARCH = 13
    STORE_COORDINATE = 30
    CAPUTER_COORDINATE = 32
    GET_COORDINATE = 31


class MoveTypes(IntEnum):
    ABSOLUTE = 0
    RELATIVE = 1
    COORDINATE = 2


class ParameterCommands(IntEnum):
    SET_AXIS_PARAMETER = 5
    GET_AXIS_PARAMETER = 6
    STORE_AXIS_PARAMETER_INTO_EEPROM = 7
    RESTORE_AXIS_PARAMETER_FROM_EEPROM = 8
    SET_GLOBAL_PARAMETER = 9
    GET_GLOBAL_PARAMETER = 10
    STORE_GLOBAL_PARAMETER_INTO_EEPROM = 11
    RESTORE_GLOBAL_PARAMETER_FROM_EEPROM = 12


class IOPortCommnds(IntEnum):
    SET_OUTPUT = 14
    GET_INPUT = 15
    ACCESS_TO_EXTERNAL_SPI_DEVICE = 29


class ControlCommands(IntEnum):
    JUMP_ALWAYS = 22
    JUMP_CONDITIONAL = 21
    COMPARE_ACCUMULATOR_WITH_CONSTANT_VALUE = 20
    CLEAR_ERROR_FLAGS = 36
    CALL_SUBROUTINE = 23
    RETURN_FROM_SUBROUTINE = 24
    WAIT_FOR_A_SPECIFIED_EVENT = 27
    END_OF_A_TMCL_PROGRAM = 28


class CalculationCommands(IntEnum):
    CALCULATE_USING_THE_ACCUMULATOR_AND_A_CONSTANT_VALUE = 19
    CALCULATE_USING_THE_ACCUMULATOR_AND_THE_X_REGISTER = 33
    COPY_ACCUMULATOR_TO_AN_AXIS_PARAMETER = 34
    COPY_ACCUMULATOR_TO_A_GLOBAL_PARAMETER = 35


class BaudRates(IntEnum):
    BAUD_9600 = 0
    BAUD_14400 = 1
    BAUD_19200 = 2
    BAUD_28800 = 3
    BAUD_38400 = 4
    BAUD_57600 = 5
    # There are higher baud rates, but there is a note that they are not supported by Windows or the error rate is high


class AxisParameters(IntEnum):
    TARGET_POSITION = 0
    ACTUAL_POSITION = 1
    TARGET_SPEED = 2
    ACTUAL_SPEED = 3
    MAX_POSITIONING_SPEED = 4
    MAX_ACCELERATION = 5
    ABSOLUTE_MAX_CURRENT = 6
    STANDBY_CURRENT = 7
    TARGET_POS_REACHED = 8
    REF_SWITCH_STATUS = 9
    RIGHT_LIMIT_SWITCH_STATUS = 10
    LEFT_LIMIT_SWITCH_STATUS = 11
    RIGHT_LIMIT_SWITCH_DISABLE = 12
    LEFT_LIMIT_SWITCH_DISABLE = 13


class AdvancedAxisParameters(IntEnum):
    MICROSTEP_RESOLUTION = 140
    PULSE_DIVISOR = 154 # The exponent of the scaling factor for the pulse (step) generator
    RAMP_DIVISOR = 153 # The exponent of the scaling factor for the ramp generator